# Generated by Django 5.1.2 on 2024-10-19 18:02

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        # operations에 아래와 같은 방식을 추가하는 것은 initial migration에서만 사용해야 한다.
        migrations.RunSQL(
            """
            CREATE TABLE user_activity (
                id SERIAL,  -- 자동 증가 정수형 필드
                user_id INT,
                action TEXT,
                created_at TIMESTAMP NOT NULL,
                PRIMARY KEY (id, created_at)  -- 복합 기본 키 (id와 created_at을 포함)
            ) PARTITION BY RANGE (created_at);
            """
        ),
    ]
